app:
  title: "Snake"
  width: 600
  height: 600
  fps: 60
  gui_font_size: 20
board:
  tile_size: 25.0
  row_tile_count: 20
  col_tile_count: 20
snake:
  start_direction: 2 # 1: LEFT, 2: RIGHT, 3: UP, 4: DOWN
  levels:
    - level: 1
      speed: 0.5
      body: 3 # 요게 처음 시작 몸통 개수!
    - level: 2
      speed: 0.4
      body: 6
    - level: 3
      speed: 0.3
      body: 10
    - level: 4
      speed: 0.2
      body: 15
    - level: 5
      speed: 0.1
      body: 20
    - level: 6
      speed: 0.09
      body: 25
    - level: 7
      speed: 0.08
      body: 30
    - level: 8
      speed: 0.07
      body: 35
    - level: 9
      speed: 0.06
      body: 40
    - level: 10
      speed: 0.05
      body: 50