app:
  title: "Snake"
  width: 800
  height: 800
  fps: 60
board:
  tile_size: 20.0
  row_tile_count: 20
  col_tile_count: 20
snake:
  start_body_count: 4
  start_direction: 4 # 1: LEFT, 2: RIGHT, 3: UP, 4: DOWN